apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-username: YWRtaW4=
  mongo-password: YWRtaW4=
  mongo-express-username: YWRtaW4=
  mongo-express-password: YWRtaW4=
